"""Remove legacy integer id from User

Revision ID: 9d06795d3be6
Revises: 66b55dae5a0a
Create Date: 2025-04-04 15:37:14.800396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d06795d3be6'
down_revision = '66b55dae5a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_column('id')

    with op.batch_alter_table('head', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_column('id')

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_column('id')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('head', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
